In [2]:
# LIBRARY
import array
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt

In [3]:
def gils(x):
    return x**2;

In [4]:
for N in range (0,10):
    print(N, "kuadrat sama dengan", gils(N))

0 kuadrat sama dengan 0
1 kuadrat sama dengan 1
2 kuadrat sama dengan 4
3 kuadrat sama dengan 9
4 kuadrat sama dengan 16
5 kuadrat sama dengan 25
6 kuadrat sama dengan 36
7 kuadrat sama dengan 49
8 kuadrat sama dengan 64
9 kuadrat sama dengan 81


In [5]:
# CREATING ARRAY
test = list(range(20))
testA = array.array('i', test)
testA

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
# integer array:
A = np.array([1, 4, 2, 5, 3])
A

array([1, 4, 2, 5, 3])

In [7]:
# array with interval
B = np.arange(0, 20, 2)
B
print(A,B)

[1 4 2 5 3] [ 0  2  4  6  8 10 12 14 16 18]


In [8]:
# array with interval
C = np.linspace(0, 1, 6)
C

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [9]:
# create matrix
D = np.eye(4)
D

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
tes = np.zeros((3, 5), dtype=float)
tes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.random.seed(25)
rand1 = np.random.randint(10, size=10)
rand2 = np.random.randint(10, size=(2,4))
rand3 = np.random.randint(10, size=(3,2,2))
rand4 = np.random.randint(10, size=(4,2,3))

In [12]:
a,b,c=1,2,3
print(a,b,c)

1 2 3


In [13]:
x = y = [7, 8, 9]
x[1]= 13
x

[7, 13, 9]

In [14]:
X = 200
Y = 150

if X > Y: print(X)
else: print(Y)

200


In [15]:
Z = 2*X + Y
Z

550

In [17]:
d = np.array([1,2,3])
e = np.array([3,2,1])
print(np.concatenate([d,e]))

[1 2 3 3 2 1]


In [19]:
f = np.concatenate([d,e])
f

array([1, 2, 3, 3, 2, 1])