In [51]:
# LIBRARY
import array
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt

In [52]:
def gils(x):
    return x**2;
for N in range (0,10):
    print(N, "kuadrat sama dengan", gils(N))

0 kuadrat sama dengan 0
1 kuadrat sama dengan 1
2 kuadrat sama dengan 4
3 kuadrat sama dengan 9
4 kuadrat sama dengan 16
5 kuadrat sama dengan 25
6 kuadrat sama dengan 36
7 kuadrat sama dengan 49
8 kuadrat sama dengan 64
9 kuadrat sama dengan 81


In [53]:
# CREATING ARRAY
test = list(range(20))
testA = array.array('i', test)
testA

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [54]:
# integer array:
A = np.array([1, 4, 2, 5, 3])

# array with interval
B = np.arange(0, 20, 2)

# array with interval
C = np.linspace(0, 1, 6)

print(A,B,C)

[1 4 2 5 3] [ 0  2  4  6  8 10 12 14 16 18] [0.  0.2 0.4 0.6 0.8 1. ]


In [55]:
# create matrix
D = np.eye(4)
D

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
print(D[:3, :4])

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [57]:
tes = np.zeros((3, 5), dtype=float)
tes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
np.random.seed(25)
rand1 = np.random.randint(10, size=10)
rand2 = np.random.randint(10, size=(2,4))
rand3 = np.random.randint(10, size=(3,2,2))
rand4 = np.random.randint(10, size=(4,2,3))

In [59]:
a,b,c=1,2,3
print(a,b,c)

1 2 3


In [60]:
x = y = [7, 8, 9]
x[1]= 13
x

[7, 13, 9]

In [61]:
X = 200
Y = 150

if X > Y: print(X)
else: print(Y)

200


In [62]:
Z = 2*X + Y
Z

550

In [63]:
d = np.array([1,2,3])
e = np.array([3,2,1])
print(np.concatenate([d,e]))

[1 2 3 3 2 1]


In [64]:
f = np.concatenate([d,e])
f

array([1, 2, 3, 3, 2, 1])

In [65]:
g = f.reshape((2,3))
g

array([[1, 2, 3],
       [3, 2, 1]])

In [66]:
B

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [67]:
B[::-1]

array([18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [82]:
x2 = np.array([[12, 5, 2, 4],
                [ 7, 6, 8, 8],
                [ 1, 6, 7, 7]])
x2[:2, :3] # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [83]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [79]:
x2[0, 1] = 2
x2

array([[12,  2,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [70]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
grid.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [74]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
z = np.array([[8, 5, 6], 
              [9, 1, 9]])
print(z[1:, 2:])

[[9]]
